language: rust
git:
  quiet: true

rust:
  - stable

cache:
  - cargo

os:
  - windows
  - linux
  - osx

branches:
  only:
    - master

# before_script:
#   - rustup component add clippy

script:
  # Clippy is for another day.
  # - cargo clippy -- -D warnings
  - cargo build --all-targets
  - cargo test --all-targets