[package]
name = "fontdue"
version = "0.1.0"
authors = ["Joe Cumbo <mooman219@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/fontdue"
homepage = "https://github.com/mooman219/fontdue"
repository = "https://github.com/mooman219/fontdue"
description = "A simple no_std font parser and rasterizer."
keywords = ["font", "parser", "rasterizer", "truetype", "ttf"]
categories = ["parser-implementations"]
readme = "README.md"
edition = "2018"
exclude = ["resources/**", "examples/**", "benches/**"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
hashbrown = "0.8"

[dev-dependencies]
criterion = "0.3"
rusttype = "0.8.2"

[[bench]]
name = "fontdue"
harness = false

[[bench]]
name = "rusttype"
harness = false