[package]
name = "fontdue"
version = "0.2.3"
authors = ["Joe Cumbo <mooman219@gmail.com>"]
license = "MIT"
documentation = "https://docs.rs/fontdue"
homepage = "https://github.com/mooman219/fontdue"
repository = "https://github.com/mooman219/fontdue"
description = "A simple no_std font parser and rasterizer."
keywords = ["font", "text", "truetype", "opentype", "ttf"]
categories = ["no-std", "gui"]
readme = "README.md"
edition = "2018"
exclude = ["resources/**", "examples/**", "fontdue.pgm"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
ttf-parser = {version = "0.8", default-features = false}
hashbrown = "0.8"

[dev-dependencies]
criterion = "0.3"
rusttype = "0.9.2"
ab_glyph = "0.2"
glyph_brush_layout = "0.2.0"

[[bench]]
name = "rasterize"
harness = false

[[bench]]
name = "layout"
harness = false